on:
  create:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    container:
      image: nearprotocol/contract-builder
      options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined
      env:
        RUSTFLAGS: -C link-arg=-s

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        rustup toolchain install stable
        rustup default stable
        rustup target add wasm32-unknown-unknown
        cargo build --target wasm32-unknown-unknown --release
    - name: Publish
      uses: ncipollo/release-action@v1
      with:
        artifacts: "target/wasm32-unknown-unknown/release/usn.wasm"
        token: ${{ secrets.GITHUB_TOKEN }}
